package cmd

import (
	"context"
	"crypto/tls"
	"errors"
	"flag"
	"fmt"
	"log"
	"net/http"
	"os"
	"os/signal"
	"strings"
	"sync/atomic"
	"syscall"
	"time"

	"github.com/sstark/gjfy/admin"
	"github.com/sstark/gjfy/fileio"
	"github.com/sstark/gjfy/httpio"
	"github.com/sstark/gjfy/misc"
	"github.com/sstark/gjfy/store"
	"github.com/sstark/gjfy/tokendb"
)

const (
	myName                = "gjfy"
	defaultHostname       = "localhost"
	listenDefault         = ":9154"
	expiryCheck           = 30 // minutes
	crtFile               = myName + ".crt"
	keyFile               = myName + ".key"
	TLSDefault            = false
	allowAnonymousDefault = false
	maxEntriesDefault     = store.DefaultMaxEntries

	// Timeouts. Without them a handful of idle or slow connections can hold
	// the server open indefinitely (slowloris).
	readHeaderTimeout = 10 * time.Second
	readTimeout       = 30 * time.Second
	writeTimeout      = 30 * time.Second
	idleTimeout       = 60 * time.Second
	maxHeaderBytes    = 1 << 16

	// How long a stop waits for requests in flight. Short on purpose: a
	// visitor mid-download is worth a couple of seconds, not a stuck unit.
	shutdownGrace = 5 * time.Second

	// Rate limits, per client address.
	newBurst    = 10
	newInterval = 2 * time.Second
	getBurst    = 30
	getInterval = time.Second
)

// assets holds everything that can be reloaded at runtime. It is swapped
// atomically: the SIGHUP handler runs in its own goroutine while requests are
// being served, so handlers must never read a half-updated value.
type assets struct {
	auth            tokendb.TokenDB
	css             []byte
	userMessageView string
	updated         time.Time
}

var (
	// startTime dates the embedded script for caching purposes: it changes
	// with every restart, which is exactly when a new binary can bring a new
	// version of it.
	startTime       = time.Now()
	currentAssets   atomic.Pointer[assets]
	fListen         string
	fURLBase        string
	fTLS            bool
	fAllowAnonymous bool
	fMaxEntries     int
	fStatsSocket    string
	scheme          = "http://"
)

// Log records one line per request. Secret ids are redacted: the id is the
// only credential protecting a secret, and access logs are routinely shipped
// and read by people who are not the intended recipient.
func Log(handler http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		log.Printf("%s (%s) \"%s %s %s\" \"%s\"",
			r.RemoteAddr, misc.GetRealIP(r), r.Method,
			misc.RedactPath(r.URL.Path), r.Proto,
			misc.SanitizeForLog(r.Header.Get("User-Agent"), 200))
		handler.ServeHTTP(w, r)
	})
}

func getURLBase() string {
	if fURLBase != "" {
		return fURLBase
	}
	sl := strings.Split(fListen, ":")
	port := sl[len(sl)-1]
	return fmt.Sprintf("%s%s:%s", scheme, defaultHostname, port)
}

// updateFiles returns the values for those assets the user can change during
// gjfy runtime. This is supposed to be run once at the beginning and on SIGHUP.
// The last return value contains the time of the last update.
func updateFiles() (auth tokendb.TokenDB, css []byte, userMessageView string, updated time.Time) {
	auth = tokendb.MakeTokenDB(fileio.TryReadFile(tokendb.AuthFileName))
	if auth == nil {
		log.Println("auth db could not be loaded, please fix and reload")
	}
	css = fileio.FileOrFunc(fileio.CssFileName, func(fn string) []byte {
		// default to embedded css if file not found
		return fileio.CustomCss
	})
	userMessageView = fileio.FileOrConst(fileio.UserMessageViewFilename, fileio.UserMessageViewDefaultText)
	updated = time.Now()
	return
}

// reload reads the configuration files and publishes them atomically.
func reload() {
	auth, css, umv, updated := updateFiles()
	currentAssets.Store(&assets{
		auth:            auth,
		css:             css,
		userMessageView: umv,
		updated:         updated,
	})
}

func loadedAssets() *assets {
	a := currentAssets.Load()
	if a == nil {
		return &assets{}
	}
	return a
}

// serverFlags builds the flag set for the server subcommand.
func serverFlags() *flag.FlagSet {
	fs := flag.NewFlagSet("gjfy server", flag.ExitOnError)
	fs.Usage = func() {
		fmt.Fprint(fs.Output(), `Run the gjfy web service, listening and waiting for users to retrieve secrets.

usage: gjfy server [flags]

flags:
`)
		fs.PrintDefaults()
	}
	stringVar(fs, &fListen, "listen", "l", listenDefault, "Listen on IP:port")
	stringVar(fs, &fURLBase, "urlbase", "u", "", "Base URL (will be generated by default)")
	boolVar(fs, &fTLS, "tls", "s", TLSDefault, "Use TLS connection")
	boolVar(fs, &fAllowAnonymous, "allow-anonymous", "a", allowAnonymousDefault, "Allow secrets by anonymous users")
	intVar(fs, &fMaxEntries, "max-entries", "m", maxEntriesDefault, "Maximum number of secrets held in memory")
	stringVar(fs, &fStatsSocket, "stats-socket", "S", "",
		"Path of a unix socket answering how many secrets are held (empty: no socket)")
	return fs
}

// buildMux wires up all routes. It is separate from the command so that tests
// can exercise the fully assembled server.
func buildMux(memstore *store.SecretStore, urlbase string) http.Handler {
	getAuth := func() tokendb.TokenDB { return loadedAssets().auth }
	getMessage := func() string { return loadedAssets().userMessageView }

	newLimiter := misc.NewLimiter(newBurst, newInterval)
	getLimiter := misc.NewLimiter(getBurst, getInterval)

	mux := http.NewServeMux()

	// View handlers
	mux.Handle("/", httpio.HandleIndex(fAllowAnonymous))
	mux.Handle(httpio.Get, misc.RateLimit(getLimiter,
		httpio.HandleGet(memstore, urlbase, getMessage)))
	mux.Handle(httpio.Info, misc.RateLimit(newLimiter,
		httpio.HandleInfo(memstore, urlbase, getAuth)))
	if fAllowAnonymous {
		mux.Handle(httpio.Create, misc.RateLimit(newLimiter,
			httpio.HandleCreate(memstore, urlbase)))
	}

	// API handlers
	mux.Handle(httpio.ApiGet, misc.RateLimit(getLimiter,
		httpio.HandleApiGet(memstore, urlbase)))
	mux.Handle(httpio.ApiNew, misc.RateLimit(newLimiter,
		httpio.HandleApiNew(memstore, urlbase, getAuth)))

	// Static handlers
	mux.Handle(httpio.Fav, httpio.HandleStaticFav())
	mux.Handle(httpio.Css, httpio.HandleStaticCss(func() ([]byte, time.Time) {
		a := loadedAssets()
		return a.css, a.updated
	}))
	mux.Handle(httpio.Js, httpio.HandleStaticJs(startTime))
	mux.Handle(httpio.ClientShell, httpio.HandleStaticClientShellScript(urlbase))

	return misc.SecurityHeaders(Log(mux), fTLS)
}

// runServer starts the gjfy web service, listening and waiting for users to
// retrieve secrets.
func runServer(args []string) {
	fs := serverFlags()
	// ExitOnError, so a bad flag has already terminated the process here.
	_ = fs.Parse(args)
	if fs.NArg() > 0 {
		log.Fatalf("unexpected argument %q", fs.Arg(0))
	}
	log.Printf("gjfy version %s\n", versionOrDevel())

	memstore := store.New(fMaxEntries)
	go memstore.Expiry(time.Minute * expiryCheck)

	// Root-only introspection, off unless a path was given. See package admin
	// for why this is a socket and not a route.
	stats, err := admin.Serve(fStatsSocket, memstore, startTime)
	switch {
	case err != nil:
		// Deliberately not fatal. The service exists to hold secrets; a
		// missing report about them is an inconvenience, while exiting here
		// would meet Restart=always and turn every cause — a sandbox that
		// forbids unix sockets, a read-only directory, a typo in the path —
		// into a crash loop that destroys the whole store.
		log.Printf("stats socket unavailable, continuing without it: %s\n", err)
	case stats != nil:
		log.Printf("answering stats on %s\n", fStatsSocket)
	}

	reload()

	sighup := make(chan os.Signal, 1)
	signal.Notify(sighup, syscall.SIGHUP)
	go func() {
		for range sighup {
			log.Println("reloading configuration...")
			reload()
		}
	}()

	if fTLS {
		scheme = "https://"
	}
	log.Printf("holding at most %d secrets in memory\n", fMaxEntries)

	srv := &http.Server{
		Addr:              fListen,
		Handler:           buildMux(memstore, getURLBase()),
		ReadHeaderTimeout: readHeaderTimeout,
		ReadTimeout:       readTimeout,
		WriteTimeout:      writeTimeout,
		IdleTimeout:       idleTimeout,
		MaxHeaderBytes:    maxHeaderBytes,
	}

	stopped := shutdownOnSignal(srv, stats, memstore)

	log.Printf("using '%s' as URL base\n", getURLBase())
	if fTLS {
		cf := fileio.TryFile(crtFile)
		if cf == "" {
			log.Fatalf("unable to open %s\n", crtFile)
		}
		kf := fileio.TryFile(keyFile)
		if kf == "" {
			log.Fatalf("unable to open %s\n", keyFile)
		}
		srv.TLSConfig = &tls.Config{MinVersion: tls.VersionTLS12}
		log.Println("listening on", fListen, "with TLS")
		err = srv.ListenAndServeTLS(cf, kf)
	} else {
		log.Println("listening on", fListen, "without TLS")
		err = srv.ListenAndServe()
	}
	if !errors.Is(err, http.ErrServerClosed) {
		log.Fatal(err)
	}
	<-stopped
	log.Println("stopped")
}

// shutdownOnSignal turns SIGTERM/SIGINT into an orderly stop and, on the way
// out, records what the stop costs.
//
// The count matters because it is unknowable afterwards: the store is memory
// only, so a restart takes every live link with it and leaves nothing behind
// to count. A line in the journal is the only place that number can survive.
func shutdownOnSignal(srv *http.Server, stats *admin.Server, memstore *store.SecretStore) <-chan struct{} {
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)
	return shutdownWhen(sig, func() { signal.Stop(sig) }, srv, stats, memstore)
}

// shutdownWhen is shutdownOnSignal without the signal plumbing, so that the
// stop can be exercised by a test.
//
// release hands the signals back to the runtime. It matters: a registration
// that outlives this goroutine swallows every later SIGTERM, and the process
// then cannot be stopped by the usual means at all.
func shutdownWhen(sig <-chan os.Signal, release func(), srv *http.Server, stats *admin.Server, memstore *store.SecretStore) <-chan struct{} {
	done := make(chan struct{})
	go func() {
		defer close(done)
		defer release()
		s := <-sig
		log.Println(stopNotice(s, memstore.Len()))
		stats.Close()
		ctx, cancel := context.WithTimeout(context.Background(), shutdownGrace)
		defer cancel()
		if err := srv.Shutdown(ctx); err != nil {
			log.Printf("shutdown: %s\n", err)
		}
	}()
	return done
}

// stopNotice is the line that survives the stop. It names the count even when
// it is zero: "nothing was lost" is worth as much in a journal as a number.
//
// The count is taken when the signal arrives, not after requests in flight
// have drained: a reveal during those few seconds shifts it by one. Taking it
// later would be more exact and less reliable — if the stop is then cut short
// by SIGKILL, the number is not written down at all.
func stopNotice(sig os.Signal, live int) string {
	return fmt.Sprintf("got %s, stopping: %d live secret(s) will be lost", sig, live)
}
